name: qiniu_base_sdk
version: 0.0.1
homepage: https://github.com/qiniu/dart-sdk
description: The sdk basic of Qiniu products

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  dio: ^3.0.10
  crypto: ^2.1.5
  meta: ^1.2.3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  dotenv: ^1.0.0
