name: qiniu_sdk_base
version: 0.7.2
homepage: https://github.com/qiniu/dart-sdk
description: The sdk basic of Qiniu products

false_secrets:
  - /test/auth/auth_test.dart

environment:
  sdk: ">=3.0.0 <4.0.0"

# 这里引入依赖时，注意依赖需要同时支持Dart和Flutter
# 同时需要尽量覆盖全平台
# 对于不能覆盖全平台的依赖，使用时需要写相关代码进行屏蔽或降级处理
dependencies:
  # 全平台支持的库
  dio: ^5.4.0
  crypto: ^3.0.3
  meta: ^1.15.0
  path: ^1.8.0
  version: ^3.0.2
  convert: ^3.1.1
  singleflight: ^1.0.2
  mutex: ^3.1.0
  platform_info: ^4.0.0

dev_dependencies:
  test: any
  lints: any
  dotenv: ^4.1.0
  coverage: "^1.6.3"
  shelf: ^1.4.1
  shelf_router: ^1.1.4
