name: qiniu_sdk_base
version: 0.6.3
homepage: https://github.com/qiniu/dart-sdk
description: The sdk basic of Qiniu products

false_secrets:
  - /test/auth/auth_test.dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.4.0
  crypto: ^3.0.0
  meta: ^1.10.0
  path: ^1.8.0

dev_dependencies:
  test: any
  lints: any
  dotenv: ^4.1.0
  coverage: "^1.6.3"
