name: qiniu_sdk_base
version: 0.3.0
homepage: https://github.com/qiniu/dart-sdk
description: The sdk basic of Qiniu products

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.0
  crypto: ^3.0.0
  meta: ^1.3.0
  os_detect: 2.0.0-nullsafety.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  dotenv: 3.0.0-nullsafety.0
  coverage: "^1.0.2"
