name: qiniu_sdk_base_diox
version: 0.4.2
homepage: https://github.com/qiniu/dart-sdk
description: The sdk basic of Qiniu products

false_secrets:
  - /test/auth/auth_test.dart

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  diox: ^5.0.0
  crypto: ^3.0.0
  meta: ^1.3.0
  uuid: ^3.0.5
  path: ^1.8.0

dev_dependencies:
  test:
  lints:
  dotenv: ^4.1.0
  coverage: "^1.6.3"
