name: Build example app and upload to artifact file

on:
  push:
  pull_request: { branches: [master] }

jobs:
  build-android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./flutter/example
    steps:
      - uses: nelonoel/branch-name@v1.0.1
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with: { length: 7 }

      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: { channel: stable, cache: true }
      - name: üèóÔ∏è Build Apk (arm64,x64,arm)
        run: flutter build apk --split-per-abi --target-platform android-arm64,android-x64,android-arm

      - name: Upload armeabi-v7a apk artifact File
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BRANCH_NAME }}-${{ env.SHA }}-app-armeabi-v7a-release.apk
          path: flutter/example/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk

      - name: Upload arm64-v8a apk artifact File
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BRANCH_NAME }}-${{ env.SHA }}-app-arm64-v8a-release.apk
          path: flutter/example/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk

      - name: Upload x86_64 apk artifact File
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BRANCH_NAME }}-${{ env.SHA }}-app-x86_64-release.apk
          path: flutter/example/build/app/outputs/flutter-apk/app-x86_64-release.apk

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./flutter/example
    steps:
      - uses: nelonoel/branch-name@v1.0.1
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with: { length: 7 }

      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with: { channel: stable, cache: true }

      - run: |
          flutter config --enable-windows-desktop
          flutter pub get
          flutter build windows

      - name: Upload Windows build file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BRANCH_NAME }}-${{ env.SHA }}-windows-x86_64.zip
          path: flutter/example/build/windows/x64/runner/Release

  build-ios:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./flutter/example
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - uses: subosito/flutter-action@v2
        with: { channel: stable, cache: true }

      - name: üèóÔ∏è Build iOS
        run: flutter build ios --no-codesign

  build-macos:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./flutter/example
    steps:
      - uses: nelonoel/branch-name@v1.0.1
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with: { length: 7 }
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with: { channel: stable, cache: true }

      # Building
      - name: Build macOS
        run: |
          flutter config --enable-macos-desktop
          flutter pub get
          flutter build macos --release

      - name: Upload web File
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BRANCH_NAME }}-${{ env.SHA }}-macos.zip
          path: flutter/example/build/macos/Build/Products/Release

  build-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./flutter/example
    steps:
      - uses: nelonoel/branch-name@v1.0.1
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with: { length: 7 }

      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: { channel: stable, cache: true }
      - run: |
          flutter pub get
          flutter build web --no-source-maps --no-native-null-assertions --release

      - name: Upload web File
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BRANCH_NAME }}-${{ env.SHA }}-web.zip
          path: flutter/example/build/web
